name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: make storybook-build

      - name: Deploy to GitHub Pages
        run: make storybook-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
